language: python
python:
  - "3.6"
services:
  - mysql
before_install:
  - pip install pycodestyle
  - python3 setup.py install
before_script:
  - mysql -e 'CREATE DATABASE my_db;'
  - mysql my_db < sample_table/schema.sql
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - pytest
